version: '3'

services:

mongo:

image: mongo

ports:

- "27017:27017"

env_file:

- .env

restart: always

web:

build:.

ports:

- "3000:3000"

links:

- mongo

command: node index.js

env file:

- .env